
import { CANONICAL_ECONOMY } from "./canonicalEconomy";
import { MONETIZATION_SPLITS } from "../config/monetizationSplits";

/**
 * FUNCTIONS MONETIZATION CONFIG
 * Hard-canonical bridge for legacy consumers.
 */

export const PAID_CONTENT_CONFIG = {
  CREATOR_SPLIT: MONETIZATION_SPLITS.UNLOCK_MEDIA.earner,
  CONTENT_FEE_PERCENTAGE: MONETIZATION_SPLITS.UNLOCK_MEDIA.platform,
} as const;

export const EARN_TO_CHAT_CONFIG = {
  CREATOR_SPLIT: MONETIZATION_SPLITS.CHAT.earner,
  AVALO_CUT: MONETIZATION_SPLITS.CHAT.platform,
  WORDS_PER_TOKEN: CANONICAL_ECONOMY.chat.tiers.STANDARD.wordsPerToken,
  INITIAL_DEPOSIT: CANONICAL_ECONOMY.chat.defaultDepositTokens,
  INSTANT_FEE:
    CANONICAL_ECONOMY.chat.defaultDepositTokens *
    CANONICAL_ECONOMY.chat.depositPlatformFeePct,
  MIN_ESCROW_BALANCE: 10,
} as const;

export const CALL_CONFIG = {
  VOICE: {
    AVALO_CUT_PERCENT: MONETIZATION_SPLITS.CALL.platform,
    EARNER_CUT_PERCENT: MONETIZATION_SPLITS.CALL.earner,
  },
  VIDEO: {
    AVALO_CUT_PERCENT: MONETIZATION_SPLITS.VIDEO_CALL.platform,
    EARNER_CUT_PERCENT: MONETIZATION_SPLITS.VIDEO_CALL.earner,
  },
} as const;

export const TIPS_CONFIG = {
  CREATOR_SPLIT: MONETIZATION_SPLITS.TIPS.earner,
  TIP_FEE_PERCENTAGE: MONETIZATION_SPLITS.TIPS.platform,
} as const;




